### ISSUE TITLE
Tests fail with python 3

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#13]
The [tests](https://github.com/fzesch/lagesonum/blob/master/tests/lagesonum_tests.py) fail with python 3. It seems as if the import of two modules (input_numper.py and dbhelper.py) does not occur properly and only works at runtime of the project. It works with Python 2, though. 

My errors:

With running in PyCharm 4.5:
Testing started at 21:58 ...
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pycharm\utrunner.py", line 139, in <module>
    module = loadSource(a[0])
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pycharm\utrunner.py", line 41, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "C:\Python34\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "H:\Python Scripts\lagesonum\tests\lagesonum_tests.py", line 4, in <module>
    from lagesonum.bottle_app import application, DB_PATH
  File "H:\Python Scripts\lagesonum\lagesonum\bottle_app.py", line 14, in <module>
    import input_number as ip
ImportError: No module named 'input_number'

Process finished with exit code 1

On command line:
Traceback (most recent call last):
  File "H:\Python Scripts\lagesonum\tests\lagesonum_tests.py", line 4, in <modul
e>
    from lagesonum.bottle_app import application, DB_PATH
ImportError: No module named 'lagesonum'

**Comment by fzesch** [comment]
The problem was, that due to the folder structure, Python expected 

import lagesonum.input_number
instead of import input_number

At runtime, it looked in other paths too.
